/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fdoassetfetcher;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FdoAssetFetcherTest {
    @Test void appHasAGreeting() {
        FdoAssetFetcher classUnderTest = new FdoAssetFetcher();
    }
}
